version: '3'
services:
    mysql:
        image: mysql:8.0.24
        user: 1000:1000
        restart: always
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/conf:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    web:
        image: nginx:latest
        ports:
            - ${DOCKER_PORT_HTTP}:80
        volumes_from:
            - app
        volumes:
            - ./docker/nginx/conf/dev.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/code
        links:
            - app
    app:
        build: ./docker/php-fpm/
        volumes:
            - ./:/var/www/code
